import java.awt.Desktop;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.URI;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



public class Main extends javax.swing.JFrame implements SwingListener {



    /** Creates new form Main */
    public Main() {        
        initComponents();
        if (SystemTray.isSupported()) {
            java.net.URL greySkull = Main.class.getResource("img/whiteSkull.gif");
            Image trayImage = Toolkit.getDefaultToolkit().getImage(greySkull);
            SystemTray tray = SystemTray.getSystemTray();            
            this.setIconImage(trayImage);
            jFrameAbout.setIconImage(trayImage);
            jFrameTrialUp.setIconImage(trayImage);
            try {
                trayIcon = new TrayIcon(trayImage, "AutoClick Pro",popupMenu1);
                trayIcon.setImageAutoSize(false);
                tray.add(trayIcon);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        profileObject = new Profile();
        initList();
        File current = new File(".");
        fc.setCurrentDirectory(current);
        mouseGrabber = new MouseGrabber();
        mouseGrabber.addListener(this);
        mouseGrabber.execute();
        robot = new RobotWorker();
        try {
           Thread.sleep(10000);
        } catch (Exception e) {
            
        }        
        //checkLicense();
        
    }

    public void runFreeTrial() {
        jLabelLicense.setText("Demo Version");
        jMenuItemFileLoad.setEnabled(false);;
        jMenuItemFileSave.setEnabled(false);
        freeTrial = new FreeTrial();
        freeTrial.addListener(this);
        freeTrial.execute();
    }

    public void checkLicense() {
      try {
            File file = new File(".\\bin\\AutoData");
            FileInputStream f_in = new FileInputStream(file.getCanonicalPath());
            ObjectInputStream obj_in = new ObjectInputStream(f_in);
            Object obj = obj_in.readObject();
            if (obj instanceof License) {
                License license = (License) obj;
                if (license.getType()==65) {
                    jLabelLicense.setText("Full Version");
                    //full
                } else {
                    int runAmount = license.getRunAmount();
                    System.out.println(runAmount);
                    System.out.println(license.getType());
                    if (runAmount==5) {
                        jFrameTrialUp.pack();
                        jFrameTrialUp.setVisible(true);
                        box.showConfirmDialog(rootPane, "Thank you for trying AutoClick Pro! Visit http://www.autoclickpro.com to license your copy now!", "Evaluation ",2);
                        System.exit(0);
                    } else {
                        license.incrementRunAmount();
                        updateLicense(license);
                    }
                }
                
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
            jFrameTrialUp.pack();
            jFrameTrialUp.setVisible(true);
            box.showConfirmDialog(rootPane, "License not found, contact admin@autoclickpro.com for assitance.", "Error",2);
            System.exit(0);
        }
    }


    public void initList() {
        listModelActions = new DefaultListModel();
        jListProfile.setModel(listModelActions);

    }

    public void notifyMouseMove(int theX, int theY) {
        jLabelMouseXY.setText(String.valueOf(theX) + "," +String.valueOf(theY));
    }

    public void freeTrialUp() {
        jFrameTrialUp.setBounds(this.getBounds());
        jFrameTrialUp.pack();
        trayIcon.setPopupMenu(popupMenu2);
        jFrameTrialUp.setVisible(true);
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameAbout = new javax.swing.JFrame();
        jLabelAboutTitle = new javax.swing.JLabel();
        jLabelAboutVersion = new javax.swing.JLabel();
        jLabelAboutCopyright = new javax.swing.JLabel();
        jPanelAboutInfo = new javax.swing.JPanel();
        jLabelAboutInfo1 = new javax.swing.JLabel();
        jLabelLicense = new javax.swing.JLabel();
        jButtonAboutOk = new javax.swing.JButton();
        jLabelAboutLogo = new javax.swing.JLabel();
        jPopupMenuProfile = new javax.swing.JPopupMenu();
        jMenuItemProfileDelete = new javax.swing.JMenuItem();
        jMenuItemProfileClear = new javax.swing.JMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        menuItemExit = new java.awt.MenuItem();
        menuItemAbout = new java.awt.MenuItem();
        menuItemHide = new java.awt.MenuItem();
        menuItemShow = new java.awt.MenuItem();
        menuItemStop = new java.awt.MenuItem();
        menuItemStart = new java.awt.MenuItem();
        jFrameTrialUp = new javax.swing.JFrame();
        jLabelAboutTitle1 = new javax.swing.JLabel();
        jLabelAboutVersion1 = new javax.swing.JLabel();
        jLabelAboutCopyright1 = new javax.swing.JLabel();
        jPanelAboutInfo1 = new javax.swing.JPanel();
        jLabelAboutInfo2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonAboutOk1 = new javax.swing.JButton();
        jLabelAboutLogo1 = new javax.swing.JLabel();
        popupMenu2 = new java.awt.PopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanelProfile = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProfile = new javax.swing.JList();
        jPanelSettings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProfile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFreq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDelay = new javax.swing.JTextField();
        jButtonStart = new javax.swing.JButton();
        jButtonStealth = new javax.swing.JButton();
        jPanelActions = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMoveX = new javax.swing.JTextField();
        jTextFieldMoveY = new javax.swing.JTextField();
        jButtonMoveAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldKeyStroke = new javax.swing.JTextField();
        jButtonKeyStrokeAdd = new javax.swing.JButton();
        jButtonLeftAdd = new javax.swing.JButton();
        jButtonRightAdd = new javax.swing.JButton();
        jButtonScreenShotAdd = new javax.swing.JButton();
        jLabelMouseXY = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileLoad = new javax.swing.JMenuItem();
        jMenuItemFileSave = new javax.swing.JMenuItem();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();
        jMenuItemHelpHelp = new javax.swing.JMenuItem();

        jFrameAbout.setTitle("About AutoClick Pro");
        jFrameAbout.setBackground(new java.awt.Color(255, 255, 255));
        jFrameAbout.setBounds(new java.awt.Rectangle(200, 200, 200, 200));
        jFrameAbout.setResizable(false);

        jLabelAboutTitle.setText("AutoClick Pro");

        jLabelAboutVersion.setText("Version 1.0");

        jLabelAboutCopyright.setText("Copyright © 2010 AutoClick Pro Software. All Rights Reserved.");

        jPanelAboutInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelAboutInfo1.setText("Visit http://www.autoclickpro.com for other great apps.");

        jLabelLicense.setText("Free trial version.");

        javax.swing.GroupLayout jPanelAboutInfoLayout = new javax.swing.GroupLayout(jPanelAboutInfo);
        jPanelAboutInfo.setLayout(jPanelAboutInfoLayout);
        jPanelAboutInfoLayout.setHorizontalGroup(
            jPanelAboutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutInfoLayout.createSequentialGroup()
                .addGroup(jPanelAboutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLicense)
                    .addComponent(jLabelAboutInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAboutInfoLayout.setVerticalGroup(
            jPanelAboutInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutInfoLayout.createSequentialGroup()
                .addComponent(jLabelAboutInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLicense)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jButtonAboutOk.setText("OK");
        jButtonAboutOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutOkActionPerformed(evt);
            }
        });

        jLabelAboutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acp1.png"))); // NOI18N
        jLabelAboutLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jFrameAboutLayout = new javax.swing.GroupLayout(jFrameAbout.getContentPane());
        jFrameAbout.getContentPane().setLayout(jFrameAboutLayout);
        jFrameAboutLayout.setHorizontalGroup(
            jFrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAboutLayout.createSequentialGroup()
                .addGroup(jFrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutLogo))
                    .addGroup(jFrameAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutTitle))
                    .addGroup(jFrameAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutVersion)))
                .addContainerGap())
            .addGroup(jFrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAboutCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE)
                .addGap(68, 68, 68))
            .addGroup(jFrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAboutInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jFrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAboutOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jFrameAboutLayout.setVerticalGroup(
            jFrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAboutLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAboutTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAboutVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAboutCopyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAboutInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAboutOk)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jMenuItemProfileDelete.setText("Delete Action");
        jMenuItemProfileDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileDeleteActionPerformed(evt);
            }
        });
        jPopupMenuProfile.add(jMenuItemProfileDelete);

        jMenuItemProfileClear.setText("Clear All");
        jMenuItemProfileClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileClearActionPerformed(evt);
            }
        });
        jPopupMenuProfile.add(jMenuItemProfileClear);

        popupMenu1.setLabel("popupMenu1");

        menuItemExit.setLabel("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemExit);

        menuItemAbout.setLabel("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemAbout);
        popupMenu1.addSeparator();
        menuItemHide.setLabel("Hide");
        menuItemHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHideActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemHide);

        menuItemShow.setLabel("Show");
        menuItemShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemShowActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemShow);
        popupMenu1.addSeparator();
        menuItemStop.setLabel("Stop");
        menuItemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStopActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemStop);

        menuItemStart.setLabel("Start");
        menuItemStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStartActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItemStart);

        jFrameTrialUp.setTitle("Thank You For Trying AutoClick Pro!");
        jFrameTrialUp.setBackground(new java.awt.Color(255, 255, 255));
        jFrameTrialUp.setBounds(new java.awt.Rectangle(200, 200, 200, 200));
        jFrameTrialUp.setResizable(false);

        jLabelAboutTitle1.setText("AutoClick Pro");

        jLabelAboutVersion1.setText("Version 1.0");

        jLabelAboutCopyright1.setText("Copyright © 2010 AutoClick Pro Software. All Rights Reserved.");

        jPanelAboutInfo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelAboutInfo2.setText("Visit http://www.autoclickpro.com to license your copy now!");

        jLabel7.setText("admin@www.autoclickpro.com");

        jLabel9.setText("Thank you for trying out AutoClick Pro!");

        javax.swing.GroupLayout jPanelAboutInfo1Layout = new javax.swing.GroupLayout(jPanelAboutInfo1);
        jPanelAboutInfo1.setLayout(jPanelAboutInfo1Layout);
        jPanelAboutInfo1Layout.setHorizontalGroup(
            jPanelAboutInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutInfo1Layout.createSequentialGroup()
                .addGroup(jPanelAboutInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelAboutInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanelAboutInfo1Layout.setVerticalGroup(
            jPanelAboutInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutInfo1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jLabelAboutInfo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jButtonAboutOk1.setText("OK");
        jButtonAboutOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutOk1ActionPerformed(evt);
            }
        });

        jLabelAboutLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acp1.png"))); // NOI18N
        jLabelAboutLogo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jFrameTrialUpLayout = new javax.swing.GroupLayout(jFrameTrialUp.getContentPane());
        jFrameTrialUp.getContentPane().setLayout(jFrameTrialUpLayout);
        jFrameTrialUpLayout.setHorizontalGroup(
            jFrameTrialUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                .addGroup(jFrameTrialUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutLogo1))
                    .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutTitle1))
                    .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAboutVersion1)))
                .addContainerGap())
            .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAboutCopyright1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE)
                .addGap(68, 68, 68))
            .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAboutInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jFrameTrialUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAboutOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jFrameTrialUpLayout.setVerticalGroup(
            jFrameTrialUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameTrialUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAboutLogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAboutTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAboutVersion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAboutCopyright1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAboutInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAboutOk1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        popupMenu2.setLabel("popupMenu2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoClick Pro");
        setBounds(new java.awt.Rectangle(250, 250, 250, 250));
        setResizable(false);

        jPanelProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile"));

        jListProfile.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Add Actions..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListProfile.setComponentPopupMenu(jPopupMenuProfile);
        jScrollPane1.setViewportView(jListProfile);

        javax.swing.GroupLayout jPanelProfileLayout = new javax.swing.GroupLayout(jPanelProfile);
        jPanelProfile.setLayout(jPanelProfileLayout);
        jPanelProfileLayout.setHorizontalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelProfileLayout.setVerticalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        jPanelSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jLabel1.setText("Profile:");

        jTextFieldProfile.setText("custom");
        jTextFieldProfile.setToolTipText("Profile name");

        jLabel2.setText("Freq:");

        jTextFieldFreq.setText("30");
        jTextFieldFreq.setToolTipText("Time in seconds to perform the set of actions");

        jLabel3.setText("Delay:");

        jTextFieldDelay.setText("1");
        jTextFieldDelay.setToolTipText("Time in seconds to delay between actions");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStealth.setText("Hide");
        jButtonStealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStealthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDelay)
                    .addComponent(jTextFieldFreq)
                    .addComponent(jTextFieldProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButtonStealth, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelActions.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        jLabel4.setText("Mouse Move");

        jTextFieldMoveX.setText("X");

        jTextFieldMoveY.setText("Y");

        jButtonMoveAdd.setText("+");
        jButtonMoveAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Key Stroke");

        jTextFieldKeyStroke.setEditable(false);
        jTextFieldKeyStroke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyStrokeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldKeyStrokeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldKeyStrokeKeyTyped(evt);
            }
        });

        jButtonKeyStrokeAdd.setText("+");

        jButtonLeftAdd.setText("Left Click");
        jButtonLeftAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftAddActionPerformed(evt);
            }
        });

        jButtonRightAdd.setText("Right Click");
        jButtonRightAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightAddActionPerformed(evt);
            }
        });

        jButtonScreenShotAdd.setText("Screenshot");
        jButtonScreenShotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScreenShotAddActionPerformed(evt);
            }
        });

        jLabelMouseXY.setText("1000 , 1000");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionsLayout = new javax.swing.GroupLayout(jPanelActions);
        jPanelActions.setLayout(jPanelActionsLayout);
        jPanelActionsLayout.setHorizontalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionsLayout.createSequentialGroup()
                        .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelActionsLayout.createSequentialGroup()
                                .addComponent(jTextFieldMoveX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMoveY, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldKeyStroke))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActionsLayout.createSequentialGroup()
                                .addComponent(jButtonMoveAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMouseXY))
                            .addComponent(jButtonKeyStrokeAdd)))
                    .addGroup(jPanelActionsLayout.createSequentialGroup()
                        .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonScreenShotAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLeftAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRightAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelActionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanelActionsLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton2))))))
        );
        jPanelActionsLayout.setVerticalGroup(
            jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionsLayout.createSequentialGroup()
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMoveX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMoveY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMoveAdd)
                    .addComponent(jLabelMouseXY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldKeyStroke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKeyStrokeAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLeftAdd)
                    .addComponent(jButton1))
                .addGroup(jPanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActionsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRightAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonScreenShotAdd))
                    .addGroup(jPanelActionsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenuFile.setText("File");

        jMenuItemFileLoad.setText("Load");
        jMenuItemFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileLoad);

        jMenuItemFileSave.setText("Save");
        jMenuItemFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileSave);

        jMenuItemFileExit.setText("Exit");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBarMain.add(jMenuFile);

        jMenuHelp.setText("Help");

        jMenuItemHelpAbout.setText("About");
        jMenuItemHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuItemHelpHelp.setText("Help");
        jMenuItemHelpHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpHelpActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpHelp);

        jMenuBarMain.add(jMenuHelp);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelActions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if (jButtonStart.getText().equalsIgnoreCase("start")) {
            if (listModelActions.size() < 1) {
                box.showConfirmDialog(rootPane, "No actions added to profile", "Profile Error", 2);
                System.out.println("no actions");
                return;
            }
            System.out.println("Starting...");

            profileObject.setModel(listModelActions);
            profileObject.setName(jTextFieldProfile.getText());
            int delay = Integer.parseInt(jTextFieldDelay.getText()) * 1000;
            profileObject.setDelay(delay);
            profileObject.setFreq(Integer.parseInt(jTextFieldFreq.getText()));
            robot = new RobotWorker();
            robot.setProfile(profileObject);
            robot.execute();
            jButtonStart.setText("Stop");
        } else {
        if (jButtonStart.getText().equalsIgnoreCase("stop")) {
            System.out.println("Stoping...");
            robot.stopWorker();
            robot = null;
            jButtonStart.setText("Start");
        }
        }


    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jTextFieldKeyStrokeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyStrokeKeyTyped
        
    }//GEN-LAST:event_jTextFieldKeyStrokeKeyTyped

    private void jTextFieldKeyStrokeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyStrokeKeyPressed
        int keyCode = evt.getKeyCode();
        String stringCode = KeyEvent.getKeyText(keyCode);
        jTextFieldKeyStroke.setText(stringCode);
    }//GEN-LAST:event_jTextFieldKeyStrokeKeyPressed

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void jTextFieldKeyStrokeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyStrokeKeyReleased

    }//GEN-LAST:event_jTextFieldKeyStrokeKeyReleased

    private void jMenuItemHelpHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpHelpActionPerformed
        try {
            Desktop desktop = Desktop.getDesktop();
            URI uri = new URI("http://www.google.com");
            desktop.browse(uri);    
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }


    }//GEN-LAST:event_jMenuItemHelpHelpActionPerformed

    private void jButtonAboutOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutOkActionPerformed
        jFrameAbout.setVisible(false);
}//GEN-LAST:event_jButtonAboutOkActionPerformed

    private void jMenuItemHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpAboutActionPerformed
        jFrameAbout.setBounds(this.getBounds());
        jFrameAbout.pack();
        jFrameAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItemHelpAboutActionPerformed

    private void jMenuItemProfileDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileDeleteActionPerformed
        listModelActions.removeElement(jListProfile.getSelectedValue());
    }//GEN-LAST:event_jMenuItemProfileDeleteActionPerformed

    private void jMenuItemFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileSaveActionPerformed
        try {
            fc.setDialogTitle("Save AutoCick Profile");
            fc.showSaveDialog(this);
            File saveFile = fc.getSelectedFile();
            String profileName = jTextFieldProfile.getText().trim();
            FileOutputStream f_out = new FileOutputStream(saveFile);
            ObjectOutputStream obj_out = new ObjectOutputStream(f_out);
            profileObject.setName(jTextFieldProfile.getText());
            profileObject.setFreq(Integer.parseInt(jTextFieldFreq.getText()));
            profileObject.setDelay(Integer.parseInt(jTextFieldDelay.getText()));
            profileObject.setModel(listModelActions);
            obj_out.writeObject(profileObject);
            System.out.println("Saved profile " + profileName);

        } catch (Exception e) {
            System.out.println("Error: "+e);
        }

    }//GEN-LAST:event_jMenuItemFileSaveActionPerformed

    private void jMenuItemFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileLoadActionPerformed
        try {
            fc.setDialogTitle("Open AutoClick Profile");
            fc.showOpenDialog(this);
            String filename = fc.getSelectedFile().getCanonicalPath();
            FileInputStream f_in = new FileInputStream(filename);
            ObjectInputStream obj_in = new ObjectInputStream(f_in);
            Object obj = obj_in.readObject();
            if (obj instanceof Profile) {
                System.out.println("Loading profile...");
                profileObject = (Profile) obj;
                jTextFieldProfile.setText(profileObject.getName());
                jTextFieldFreq.setText(String.valueOf(profileObject.getFreq()));
                jTextFieldDelay.setText(String.valueOf(profileObject.getDelay()));
                jListProfile.setModel(profileObject.getModelActions());
                listModelActions = profileObject.getModelActions();
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }

    }//GEN-LAST:event_jMenuItemFileLoadActionPerformed

    private void jButtonLeftAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftAddActionPerformed
        Action action = new Action();
        action.setDisplayName("Left Click");
        action.setType("LClick");
        listModelActions.addElement(action);
    }//GEN-LAST:event_jButtonLeftAddActionPerformed

    private void jMenuItemProfileClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileClearActionPerformed
        listModelActions.clear();
    }//GEN-LAST:event_jMenuItemProfileClearActionPerformed

    private void jButtonMoveAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveAddActionPerformed
        try {
        Action action = new Action();
        action.setDisplayName("Move " + jTextFieldMoveX.getText() + " " + jTextFieldMoveY.getText());
        action.setType("Move");
        action.setX(Integer.parseInt(jTextFieldMoveX.getText()));
        action.setY(Integer.parseInt(jTextFieldMoveY.getText()));
        listModelActions.addElement(action);
        } catch (Exception e) {
            box.showConfirmDialog(rootPane, "Mouse move values must be numeric", "Profile Error", 2);
        }
    }//GEN-LAST:event_jButtonMoveAddActionPerformed

    private void jButtonRightAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightAddActionPerformed
        Action action = new Action();
        action.setDisplayName("Right Click");
        action.setType("RClick");
        listModelActions.addElement(action);
    }//GEN-LAST:event_jButtonRightAddActionPerformed

    private void jButtonScreenShotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScreenShotAddActionPerformed
        Action action = new Action();
        action.setDisplayName("Screenshot");
        action.setType("Screenshot");
        listModelActions.addElement(action);
    }//GEN-LAST:event_jButtonScreenShotAddActionPerformed

    private void jButtonStealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStealthActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStealthActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHideActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_menuItemHideActionPerformed

    private void menuItemShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemShowActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_menuItemShowActionPerformed

    private void menuItemStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStartActionPerformed
        jButtonStart.doClick();
    }//GEN-LAST:event_menuItemStartActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        jFrameAbout.setBounds(this.getBounds());
        jFrameAbout.pack();
        jFrameAbout.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void jButtonAboutOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutOk1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAboutOk1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        License license = new License();
        license.setRunAmount(0);
        license.setType(66);

        try {
            FileOutputStream f_out = new FileOutputStream("AutoData");
            ObjectOutputStream obj_out = new ObjectOutputStream(f_out);
            obj_out.writeObject(license);
            System.out.println("Created Licesne.");
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuItemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStopActionPerformed
        try {            
            System.out.println("Stoping...");
            robot.cancel(false);
            robot = null;
            jButtonStart.setText("Start");
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_menuItemStopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    public void updateLicense(License theLicense) {
        try {
            File file = new File(".\\bin\\AutoData");
            FileOutputStream f_out = new FileOutputStream(file.getCanonicalPath());
            ObjectOutputStream obj_out = new ObjectOutputStream(f_out);
            obj_out.writeObject(theLicense);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (Exception e) {
            System.out.println("Error:" + e );
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAboutOk;
    private javax.swing.JButton jButtonAboutOk1;
    private javax.swing.JButton jButtonKeyStrokeAdd;
    private javax.swing.JButton jButtonLeftAdd;
    private javax.swing.JButton jButtonMoveAdd;
    private javax.swing.JButton jButtonRightAdd;
    private javax.swing.JButton jButtonScreenShotAdd;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStealth;
    private javax.swing.JFrame jFrameAbout;
    private javax.swing.JFrame jFrameTrialUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAboutCopyright;
    private javax.swing.JLabel jLabelAboutCopyright1;
    private javax.swing.JLabel jLabelAboutInfo1;
    private javax.swing.JLabel jLabelAboutInfo2;
    private javax.swing.JLabel jLabelAboutLogo;
    private javax.swing.JLabel jLabelAboutLogo1;
    private javax.swing.JLabel jLabelAboutTitle;
    private javax.swing.JLabel jLabelAboutTitle1;
    private javax.swing.JLabel jLabelAboutVersion;
    private javax.swing.JLabel jLabelAboutVersion1;
    private javax.swing.JLabel jLabelLicense;
    private javax.swing.JLabel jLabelMouseXY;
    private javax.swing.JList jListProfile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemFileLoad;
    private javax.swing.JMenuItem jMenuItemFileSave;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JMenuItem jMenuItemHelpHelp;
    private javax.swing.JMenuItem jMenuItemProfileClear;
    private javax.swing.JMenuItem jMenuItemProfileDelete;
    private javax.swing.JPanel jPanelAboutInfo;
    private javax.swing.JPanel jPanelAboutInfo1;
    private javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JPopupMenu jPopupMenuProfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDelay;
    private javax.swing.JTextField jTextFieldFreq;
    private javax.swing.JTextField jTextFieldKeyStroke;
    private javax.swing.JTextField jTextFieldMoveX;
    private javax.swing.JTextField jTextFieldMoveY;
    private javax.swing.JTextField jTextFieldProfile;
    private java.awt.MenuItem menuItemAbout;
    private java.awt.MenuItem menuItemExit;
    private java.awt.MenuItem menuItemHide;
    private java.awt.MenuItem menuItemShow;
    private java.awt.MenuItem menuItemStart;
    private java.awt.MenuItem menuItemStop;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
    private Profile profileObject;
    JFileChooser fc = new JFileChooser();
    private DefaultListModel listModelActions;
    private TrayIcon trayIcon;
    private MouseGrabber mouseGrabber;
    private FreeTrial freeTrial;
    private JOptionPane box;
    private RobotWorker robot;


}
